FROM eclipse-temurin:17-jdk-alpine@sha256:ddd7a05cf8263989c29f2a9476dcfa25d0eaf8310d400f998ebd03c0d32feb72
RUN mkdir -p /app/logs
COPY ./${moduleNameOriginal}/target/${moduleName}.jar /app/app.jar
EXPOSE 8080
WORKDIR /app

ENV JAVA_OPTS="-Xms512m -Xmx1024m"
CMD ["sh", "-c", "java $JAVA_OPTS -jar app.jar --server.port=8080"]
