--liquibase formatted sql
-- DON'T EDIT! THIS FILE GENERATED BY tezrok at 2023-03-19T15:32:54

--changeset TezrokUser:2023-03-19_153254-Initial
--comment Initial script for creating the structure

CREATE TABLE public.address (
  id BIGSERIAL PRIMARY KEY,
  street VARCHAR(255) NOT NULL,
  city VARCHAR(50) NOT NULL,
  state VARCHAR(255) NOT NULL,
  zip VARCHAR(255),
  country VARCHAR(255) NOT NULL,
  state_id INT NOT NULL
);
