CREATE TABLE example_table (
    id                   SERIAL PRIMARY KEY,
    varchar_val          VARCHAR(255),
    text_val             TEXT,
    int_val              INTEGER,
    smallint_val         SMALLINT,
    bigint_val           BIGINT,
    boolean_val          BOOLEAN,
    decimal_val          DECIMAL(10, 2),
    numeric_val          NUMERIC(10, 2),
    real_val             REAL,
    double_precision_val DOUBLE PRECISION,
    date_val             DATE,
    timestamp_val        TIMESTAMP,
    time_val             TIME,
    interval_val         INTERVAL,
    uuid_val             UUID,
    json_val             JSON,
    jsonb_val            JSONB,
    bytea_val            BYTEA
);

INSERT INTO example_table (
    varchar_val,
    text_val,
    int_val,
    smallint_val,
    bigint_val,
    boolean_val,
    decimal_val,
    numeric_val,
    real_val,
    double_precision_val,
    date_val,
    timestamp_val,
    time_val,
    interval_val,
    uuid_val,
    json_val,
    jsonb_val
) VALUES (
     'Example Varchar',
     'Example Text',
     123,
     456,
     789,
     true,
     1234.56,
     1234.56,
     1234.56,
     1234.56,
     '2023-03-19',
     '2023-03-19 15:30:00',
     '15:30:00',
     '1 day 2 hours 30 minutes',
     'a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a11',
     '{"example": "json"}',
     '{"example": "jsonb"}'
 );

