CREATE SCHEMA IF NOT EXISTS tst1;

CREATE TABLE tst1.address (
  id BIGSERIAL PRIMARY KEY,
  street VARCHAR(255) NOT NULL,
  city VARCHAR(50) NOT NULL,
  state VARCHAR(255) NOT NULL,
  zip VARCHAR(255),
  country VARCHAR(255) NOT NULL,
  state_id INT NOT NULL UNIQUE,
  UNIQUE (street),
  UNIQUE (city, zip)
);
